version: '3.9'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 80:9090
    command:
      - --config.file=/etc/prom/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=3d

      