{
 "title": "Test",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "deviceid", "query": { "query": "label_values(device_Id)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests / min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(http_request_count_total{device_Id=\"${deviceid}\"}[$__range]) / $__range_s) * 60 ",
     "legendFormat": "{{device_Id}}"
    }
   ]
  },
  {
   "title": "AVG Request Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_sum[$__range]) / increase(http_request_duration_seconds_count[$__range])"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_count_total{device_Id=\"${deviceid}\"}[1m]) * 60  ",
     "legendFormat": "{{device_Id}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_ram_usage{device_Id=\"${deviceid}\"}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_cpu_temperature{device_Id=\"${deviceid}\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[1m]) * 60",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}